// Code generated by github.com/Ccheers/protoc-gen-zeroapi. DO NOT EDIT.

package handler

import (
	svc "github.com/Ccheers/protoc-gen-zeroapi/example/internal/svc"
	rest "github.com/zeromicro/go-zero/rest"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Ccheers/protoc-gen-zeroapi package it is being compiled against.
func Register_BlogServiceHandlers(server *rest.Server, svcCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "GET",
					Path:    "/v1/author/:author_id/articles",
					Handler: GetArticles_0_Handler(svcCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "GET",
					Path:    "/v1/articles",
					Handler: GetArticles_1_Handler(svcCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "POST",
					Path:    "/v1/author/:author_id/articles",
					Handler: CreateArticle_0_Handler(svcCtx),
				},
			}...,
		),
	)

}
