// Code generated by github.com/Ccheers/protoc-gen-zeroapi. DO NOT EDIT.

package handler

import (
	http1 "github.com/Ccheers/bind/http"
	v1 "github.com/Ccheers/protoc-gen-zeroapi/example/api/product/app/v1"
	logic "github.com/Ccheers/protoc-gen-zeroapi/example/internal/logic"
	svc "github.com/Ccheers/protoc-gen-zeroapi/example/internal/svc"
	rest "github.com/zeromicro/go-zero/rest"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Ccheers/protoc-gen-zeroapi package it is being compiled against.
func Register_BlogServiceHandlers(server *rest.Server, svcCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "GET",
					Path:    "/v1/author/:author_id/articles",
					Handler: GetArticles_0_Handler(svcCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "GET",
					Path:    "/v1/articles",
					Handler: GetArticles_1_Handler(svcCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "POST",
					Path:    "/v1/author/:author_id/articles",
					Handler: CreateArticle_0_Handler(svcCtx),
				},
			}...,
		),
	)

}
func GetArticles_0_Handler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req v1.GetArticlesReq
		http1.TryMyBestBind(r, &req)
		if validate, ok := (interface{})(&req).(interface{ Validate() error }); ok {
			err := validate.Validate()
			if err != nil {
				svcCtx.ResponseEncodeFunc(r, w, nil, err)
				return
			}
		}
		l := logic.NewGetArticlesLogic(r.Context(), svcCtx)
		resp, err := l.GetArticles(&req)
		svcCtx.ResponseEncodeFunc(r, w, resp, err)
	}
}
func GetArticles_1_Handler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req v1.GetArticlesReq
		http1.TryMyBestBind(r, &req)
		if validate, ok := (interface{})(&req).(interface{ Validate() error }); ok {
			err := validate.Validate()
			if err != nil {
				svcCtx.ResponseEncodeFunc(r, w, nil, err)
				return
			}
		}
		l := logic.NewGetArticlesLogic(r.Context(), svcCtx)
		resp, err := l.GetArticles(&req)
		svcCtx.ResponseEncodeFunc(r, w, resp, err)
	}
}
func CreateArticle_0_Handler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req v1.Article
		http1.TryMyBestBind(r, &req)
		if validate, ok := (interface{})(&req).(interface{ Validate() error }); ok {
			err := validate.Validate()
			if err != nil {
				svcCtx.ResponseEncodeFunc(r, w, nil, err)
				return
			}
		}
		l := logic.NewCreateArticleLogic(r.Context(), svcCtx)
		resp, err := l.CreateArticle(&req)
		svcCtx.ResponseEncodeFunc(r, w, resp, err)
	}
}
