// Code generated by github.com/Ccheers/protoc-gen-zeroapi. DO NOT EDIT.

package handler

import (
	v1 "github.com/Ccheers/protoc-gen-zeroapi/example/api/product/app/v1"
	logic "github.com/Ccheers/protoc-gen-zeroapi/example/internal/logic"
	svc "github.com/Ccheers/protoc-gen-zeroapi/example/internal/svc"
	rest "github.com/zeromicro/go-zero/rest"
	httpx "github.com/zeromicro/go-zero/rest/httpx"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Ccheers/protoc-gen-zeroapi package it is being compiled against.
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "GET",
					Path:    "/v1/author/:author_id/articles",
					Handler: GetArticles_0_Handler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "GET",
					Path:    "/v1/articles",
					Handler: GetArticles_1_Handler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{},
			[]rest.Route{
				{
					Method:  "POST",
					Path:    "/v1/author/:author_id/articles",
					Handler: CreateArticle_0_Handler(serverCtx),
				},
			}...,
		),
	)

}
func GetArticles_0_Handler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req v1.GetArticlesReq
		l := logic.NewGetArticlesLogic(r.Context(), svcCtx)
		resp, err := l.GetArticles(&req)
		if err != nil {
			httpx.Error(w, err)
			return
		}
		httpx.WriteJson(w, http.StatusOK, resp)
	}
}
func GetArticles_1_Handler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req v1.GetArticlesReq
		l := logic.NewGetArticlesLogic(r.Context(), svcCtx)
		resp, err := l.GetArticles(&req)
		if err != nil {
			httpx.Error(w, err)
			return
		}
		httpx.WriteJson(w, http.StatusOK, resp)
	}
}
func CreateArticle_0_Handler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req v1.Article
		l := logic.NewCreateArticleLogic(r.Context(), svcCtx)
		resp, err := l.CreateArticle(&req)
		if err != nil {
			httpx.Error(w, err)
			return
		}
		httpx.WriteJson(w, http.StatusOK, resp)
	}
}
